AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Deliforce web Lambda'

Resources:
  ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: webstage
      Name: Web-api
      DefinitionUri: ./deliwebapi.yaml
Parameters: 
  bucketName: 
    Type: String
    Default: devuser-constant
    AllowedValues: 
      - lambda-constant
      - devuser-constant
    Description: Enter lambda-constant,devuse-constant Default is devuser-constant.
  constantFileName:
    Type: String
    Default: constant.json
    AllowedValues:
      - constant.json
    Description: Enter constant.json


  DeliforcebackgroundjobMethod:
     Type: AWS::Serverless::Function
     Properties:
       FunctionName: backGroundjob
       Timeout: 300
       Handler: index.handler
       Runtime: nodejs6.10
       CodeUri: ./backGroundJob
       Policies: AWSLambdaFullAccess
       Role: arn:aws:iam::786724127547:role/DevUser-poc
       

  DeliforceteamfetchteamsMethod:
     Type: AWS::Serverless::Function
     Properties:
       FunctionName: Deliforce_team_fetchTeam
       Timeout: 300
       Handler: index.handler
       Runtime: nodejs6.10
       CodeUri: ./Deliforce_team_fetchTeam
       Policies: AWSLambdaFullAccess
       Role: arn:aws:iam::786724127547:role/DevUser-poc
       
